import { NextPage } from "next";
import styles from "../styles/Home.module.css"; 
import Head from '../src/seo-head';
import ProductForm from "../components/ProductForm/ProductForm";

const AddProduct: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head 
                title={"Rivizta"}
                description={"Generated by create next app"} 
                ogimage={''}
            ></Head>
            <main className={styles.main}>
                <ProductForm />
            </main>
        </div>
    );
}

export default AddProduct;